sudo: required
language: java

script:
  - pwd
  - mvn clean package
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-tests -Dexec.mainClass="org.rabix.tests.TestRunner" | grep -Ev '(^\[|Download\w+:)'
